export const destinations = [
{id:'bwindi',name:'Bwindi Impenetrable National Park',short:'Bwindi Impenetrable',category:'national-park',region:'Southwest Uganda',rating:4.8,reviews:124,lat:-1.052,lon:29.716,description:'A remarkable forest destination known for mountain gorillas, rich biodiversity and guided nature experiences.',attractions:['Gorilla trekking','Forest walks','Bird watching'],tips:'Book gorilla trekking permits early and follow park guidance.'},
{id:'murchison',name:'Murchison Falls National Park',short:'Murchison Falls',category:'national-park',region:'Northwest Uganda',rating:4.7,reviews:98,lat:2.274,lon:31.793,description:'Uganda’s largest national park, featuring the powerful Nile waterfall and diverse wildlife.',attractions:['Murchison Falls','Game drives','Boat safari'],tips:'Morning game drives and Nile boat trips are popular.'},
{id:'bunyonyi',name:'Lake Bunyonyi',short:'Lake Bunyonyi',category:'lake',region:'Southwest Uganda',rating:4.6,reviews:76,lat:-1.283,lon:29.925,description:'A scenic highland lake surrounded by terraced hills and small islands.',attractions:['Canoeing','Island visits','Scenic viewpoints'],tips:'Enjoy a boat or canoe trip and allow time for the hillside views.'},
{id:'queen',name:'Queen Elizabeth National Park',short:'Queen Elizabeth',category:'national-park',region:'Western Uganda',rating:4.7,reviews:103,lat:-0.15,lon:30.0,description:'A varied wildlife destination with savannah, crater lakes, forests and the Kazinga Channel.',attractions:['Game drives','Kazinga Channel','Nature walks'],tips:'Carry binoculars for wildlife and bird watching.'},
{id:'kampala',name:'Kampala',short:'Kampala',category:'city',region:'Central Uganda',rating:4.5,reviews:89,lat:0.3476,lon:32.5825,description:'Uganda’s lively capital with cultural landmarks, markets, food and urban experiences.',attractions:['Gaddafi Mosque','Craft markets','Cultural sites'],tips:'Plan around traffic and explore different city neighborhoods.'},
{id:'jinja',name:'Jinja',short:'Jinja',category:'outdoor',region:'Eastern Uganda',rating:4.6,reviews:91,lat:0.4479,lon:33.2026,description:'A popular adventure destination on the Nile with water activities and riverside experiences.',attractions:['Nile experiences','Adventure activities','Source of the Nile'],tips:'Choose activities from established operators and check conditions.'},
{id:'kasubi',name:'Kasubi Tombs',short:'Kasubi Tombs',category:'cultural',region:'Kampala',rating:4.4,reviews:62,lat:0.332,lon:32.553,description:'A significant cultural site associated with the Buganda Kingdom and royal heritage.',attractions:['Cultural history','Architecture','Guided tours'],tips:'Dress respectfully and follow site photography guidance.'},
{id:'rwenzori',name:'Rwenzori Mountains',short:'Rwenzori Mountains',category:'outdoor',region:'Western Uganda',rating:4.8,reviews:73,lat:0.37,lon:29.98,description:'Mountain landscapes, valleys and high-altitude hiking routes in western Uganda.',attractions:['Mountain hiking','Scenic valleys','Bird watching'],tips:'Use experienced guides and prepare for changing mountain weather.'}
];
export const getDestination=id=>destinations.find(d=>d.id===id);
